"""Property-based tests for the SRT/VTT serializer ⇄ parser round-trip.

This module hosts the property tests generated by tasks 3.4 (SRT round-trip)
and 3.5 (VTT round-trip). Additional UTF-8 / error-path properties
(tasks 3.6–3.8) can be added alongside these without changing the file
layout.

## Property 1: 字幕 SRT 往返一致性

    For any valid list of :class:`SubtitleEntry` ``entries``, serializing
    them with :meth:`SubtitleSerializer.to_srt` and then parsing the
    resulting text with :meth:`SubtitleParser.parse_srt` produces a list
    that is equivalent to ``entries`` under the relation defined in
    :mod:`translation_dubbing_skill.models.subtitle_entry`
    (``index / start_ms / end_ms / normalize_text(text)``).

**Validates: Requirements 2.1, 2.3, 3.1, 3.3, 4.1, 4.3**

## Property 2: 字幕 VTT 往返一致性

    For any valid list of :class:`SubtitleEntry` ``entries`` whose
    indices form the sequence ``1, 2, 3, ...`` (the WebVTT parser
    assigns sequential 1-based indices to every cue regardless of any
    embedded identifier line, so the input index sequence must match
    that assignment for a round-trip to be meaningful), serializing
    them with :meth:`SubtitleSerializer.to_vtt` and then parsing the
    resulting text with :meth:`SubtitleParser.parse_vtt` produces a
    list equivalent to ``entries`` under the same relation.

**Validates: Requirements 2.2, 2.3, 3.2, 3.3, 4.2, 4.3**
"""

from __future__ import annotations

import re
from typing import List

from hypothesis import given, settings
from hypothesis import strategies as st

from translation_dubbing_skill.models import SubtitleEntry, entries_equivalent
from translation_dubbing_skill.subtitle import SubtitleParser, SubtitleSerializer


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Cap at well under 24h so HH fits two digits — matches the serializer's
# ``{hours:02d}`` formatting, which is the practical subtitle domain.
_MAX_MS: int = 23 * 3_600_000 + 59 * 60_000 + 59 * 1_000 + 999

# Control characters other than TAB must be excluded: the serializer /
# parser normalise CR and LF, but arbitrary control characters (e.g. the
# vertical-tab U+000B, NUL, or DEL) are outside the subtitle text domain
# and would either break block structure or be silently re-interpreted by
# ``str.splitlines``-style handling.
_CONTROL_CHARS: set[str] = {chr(c) for c in range(0, 32)} | {chr(0x7F)}
_CONTROL_CHARS.discard("\t")  # tabs are legal inside a subtitle text line
_CONTROL_CHARS.discard("\n")  # newlines separate text lines inside a cue


def _text_line_strategy() -> st.SearchStrategy[str]:
    """A single line of subtitle text — no newlines, no other controls.

    Lines may be empty so we exercise the "blank line inside text" path
    that a naïve serializer would break on (we forbid the pathological
    ``\\n\\n`` sequence at the list level below).
    """
    return st.text(
        alphabet=st.characters(
            blacklist_characters="".join(_CONTROL_CHARS),
            # Drop surrogate halves which are never valid UTF-8 text;
            # everything else (CJK, emoji, whitespace, punctuation) is
            # fair game.
            blacklist_categories=("Cs",),
        ),
        min_size=0,
        max_size=40,
    )


_ALL_DIGITS_RE: re.Pattern[str] = re.compile(r"^\d+$")


def _is_parseable_text(text: str) -> bool:
    """Filter text values that would break SRT block structure.

    The SRT grammar is block-based with blank lines as separators, so we
    must match the serializer's Normal Form when judging "would the
    parser see a spurious block boundary?". :meth:`_normalize_text_lines`
    in the serializer:

    1. Collapses CRLF / CR → LF.
    2. Rstrips each line.

    After that transform, the domain constraints become:

    - No ``""`` (fully blank) line may appear inside a multi-line text —
      it would introduce a spurious block boundary.
    - A text line that consists entirely of digits (after rstripping) is
      indistinguishable from the *next* cue's SRT index line once the
      preceding cue's blank-line separator is in place. The equivalent
      VTT risk (lines starting with ``WEBVTT``) is handled in the VTT
      property test.
    """
    # Mirror the serializer's Normal Form pre-processing so our domain
    # filter judges the exact lines the parser will see.
    unified = text.replace("\r\n", "\n").replace("\r", "\n")
    stripped_lines = [line.rstrip() for line in unified.split("\n")]

    # Multi-line texts must have no blank line anywhere (including the
    # first or last line). A single-line empty text ``""`` — i.e. the
    # cue carries no text at all — is fine; the serializer emits just
    # the index + timestamp lines and the parser recovers an empty text.
    if len(stripped_lines) > 1 and any(line == "" for line in stripped_lines):
        return False

    for line in stripped_lines:
        if _ALL_DIGITS_RE.match(line):
            return False

    return True


def _multi_line_text_strategy() -> st.SearchStrategy[str]:
    """A subtitle text value that spans zero or more newline-separated lines."""
    return (
        st.lists(_text_line_strategy(), min_size=1, max_size=4)
        .map("\n".join)
        .filter(_is_parseable_text)
    )


def _entry_strategy(index: int) -> st.SearchStrategy[SubtitleEntry]:
    """Generate a single :class:`SubtitleEntry` with the given 1-based index."""
    return st.builds(
        lambda times, text: SubtitleEntry(
            index=index,
            start_ms=min(times),
            end_ms=max(times),
            text=text,
        ),
        times=st.tuples(
            st.integers(min_value=0, max_value=_MAX_MS),
            st.integers(min_value=0, max_value=_MAX_MS),
        ),
        text=_multi_line_text_strategy(),
    )


@st.composite
def entry_lists(draw: st.DrawFn) -> List[SubtitleEntry]:
    """Generate a list of :class:`SubtitleEntry` with unique, increasing indices.

    Indices are strictly increasing (the SRT format tolerates arbitrary
    1-based ordinals as long as they are integers — the round-trip only
    requires that each entry's own ``index`` survives). Times within a
    single entry satisfy ``start_ms <= end_ms`` by construction; the
    property does *not* require non-overlap across entries (SRT allows
    overlapping cues).
    """
    size = draw(st.integers(min_value=0, max_value=6))
    if size == 0:
        return []

    # Pick ``size`` distinct positive integers, sort ascending, and use
    # them as the ``index`` field. This matches the "strictly increasing
    # indices, no duplicates" constraint spelled out in the task brief.
    indices = sorted(
        draw(
            st.lists(
                st.integers(min_value=1, max_value=10_000),
                min_size=size,
                max_size=size,
                unique=True,
            )
        )
    )

    return [draw(_entry_strategy(idx)) for idx in indices]


# ---------------------------------------------------------------------------
# Property: parse_srt(to_srt(entries)) ≡ entries
# ---------------------------------------------------------------------------


@given(entries=entry_lists())
@settings(max_examples=200)
def test_srt_round_trip_preserves_entries(entries: List[SubtitleEntry]) -> None:
    """**Validates: Requirements 2.1, 2.3, 3.1, 3.3, 4.1, 4.3**

    For any valid ``entries`` list, ``parse_srt(to_srt(entries))`` must be
    equivalent to ``entries`` under
    :func:`translation_dubbing_skill.models.entries_equivalent`.
    """
    serializer = SubtitleSerializer()
    parser = SubtitleParser()

    serialized = serializer.to_srt(entries)
    reparsed = parser.parse_srt(serialized)

    assert entries_equivalent(reparsed, entries), (
        "round-trip mismatch\n"
        f"original: {entries!r}\n"
        f"serialized: {serialized!r}\n"
        f"reparsed: {reparsed!r}"
    )


# ---------------------------------------------------------------------------
# VTT-specific strategy and property
# ---------------------------------------------------------------------------
#
# Key difference from SRT: the VTT parser assigns sequential 1-based
# indices to every cue (``entry_index = len(entries) + 1``) regardless of
# any cue identifier emitted by the serializer. For the round-trip
# equivalence relation — which requires
# ``reparsed[i].index == original[i].index`` — to hold, the ``entries``
# we feed the serializer must already have indices ``1, 2, 3, ...`` in
# that order. The SRT filter ``_is_parseable_text`` remains sound for
# VTT: its "no blank interior lines" rule is equally required (a blank
# line inside a text value would still close the cue block prematurely
# in WebVTT), and its "no all-digit lines" rule is stricter than WebVTT
# strictly needs but removes a tiny corner of the search space that
# would have no bearing on the property being exercised.


@st.composite
def vtt_entry_lists(draw: st.DrawFn) -> List[SubtitleEntry]:
    """Generate entries with sequential 1-based indices for VTT round-trip.

    VTT cue identifiers are free-form and the parser ignores them when
    assigning ``SubtitleEntry.index``, so the only index sequence a
    round-trip can preserve is the one the parser re-derives:
    ``1, 2, 3, ..., n``.
    """
    size = draw(st.integers(min_value=0, max_value=6))
    if size == 0:
        return []
    return [draw(_entry_strategy(idx)) for idx in range(1, size + 1)]


@given(entries=vtt_entry_lists())
@settings(max_examples=200)
def test_vtt_round_trip_preserves_entries(entries: List[SubtitleEntry]) -> None:
    """**Validates: Requirements 2.2, 2.3, 3.2, 3.3, 4.2, 4.3**

    For any valid ``entries`` list with sequential 1-based indices,
    ``parse_vtt(to_vtt(entries))`` must be equivalent to ``entries``
    under :func:`translation_dubbing_skill.models.entries_equivalent`.
    """
    serializer = SubtitleSerializer()
    parser = SubtitleParser()

    serialized = serializer.to_vtt(entries)
    reparsed = parser.parse_vtt(serialized)

    assert entries_equivalent(reparsed, entries), (
        "round-trip mismatch\n"
        f"original: {entries!r}\n"
        f"serialized: {serialized!r}\n"
        f"reparsed: {reparsed!r}"
    )


# ---------------------------------------------------------------------------
# Property 3: 字幕序列化 UTF-8 安全
# ---------------------------------------------------------------------------
#
# The serializer emits a ``str`` and :meth:`SubtitleSerializer.write_file`
# writes that string with ``encoding="utf-8"`` (R3.4). This property
# asserts two related guarantees over the serialized output for any
# valid entries list whose text may include CJK ideographs, emoji
# (including multi-codepoint emoji sequences), tabs and embedded
# newlines:
#
# 1. The in-memory ``str`` returned by :meth:`to_srt` / :meth:`to_vtt`
#    survives a UTF-8 encode → decode round-trip byte-for-byte. In
#    principle any Python ``str`` containing only scalar Unicode
#    code points satisfies this, but the property is worth fixing
#    because the domain deliberately exercises boundary cases
#    (surrogate-pair emoji, ideographs above U+FFFF, tabs mixed with
#    line breaks) that sometimes trip naïve pretty-printers.
# 2. The bytes actually written to disk by :meth:`write_file` decode
#    back to the exact string that was handed in. This is the
#    observable contract for R3.4 — a downstream tool reading the file
#    must see the Unicode text verbatim with no mojibake, no BOM being
#    injected, no universal-newline translation, and no fallback to a
#    lossy encoding.
#
# Validates: Requirement 3.4


def _utf8_text_line_strategy() -> st.SearchStrategy[str]:
    """A single text line that mixes ASCII, CJK, emoji, and tabs.

    The alphabet is drawn explicitly so Hypothesis spends its example
    budget on the characters the property cares about (R3.4 calls out
    UTF-8 safety, which is uninteresting for plain ASCII). We union:

    - ASCII letters/digits/punctuation as a baseline.
    - The CJK Unified Ideographs block (U+4E00..U+9FFF) — the most
      common Chinese ideographs.
    - The Miscellaneous Symbols and Pictographs block (U+1F300..U+1F5FF)
      and the Emoticons block (U+1F600..U+1F64F), which together cover
      the emoji surrogate-pair regime that has historically been a
      UTF-8 round-trip hazard.
    - The literal TAB character, which the task brief explicitly calls
      out; the serializer's Normal Form strips *trailing* tabs but
      preserves interior tabs, so they must survive encode/decode.

    Surrogate halves (category ``Cs``) are excluded — they are not valid
    UTF-8 scalar values and Python's own ``str.encode("utf-8")`` raises
    on them, so they are outside the property's domain.
    """
    return st.text(
        alphabet=st.one_of(
            st.sampled_from("\t"),
            st.characters(
                min_codepoint=0x20,
                max_codepoint=0x7E,
                blacklist_categories=("Cs",),
            ),
            st.characters(
                min_codepoint=0x4E00,
                max_codepoint=0x9FFF,
                blacklist_categories=("Cs",),
            ),
            st.characters(
                min_codepoint=0x1F300,
                max_codepoint=0x1F5FF,
                blacklist_categories=("Cs",),
            ),
            st.characters(
                min_codepoint=0x1F600,
                max_codepoint=0x1F64F,
                blacklist_categories=("Cs",),
            ),
        ),
        min_size=0,
        max_size=20,
    )


def _utf8_multi_line_text_strategy() -> st.SearchStrategy[str]:
    """A subtitle text value that spans one or more Unicode-rich lines.

    The resulting text is filtered through :func:`_is_parseable_text`
    so it stays within the serializer's Normal Form domain (no blank
    interior lines; no all-digit lines that would collide with SRT
    index lines). The filter is compatible with CJK/emoji input
    because those characters never match ``^\\d+$``.
    """
    return (
        st.lists(_utf8_text_line_strategy(), min_size=1, max_size=3)
        .map("\n".join)
        .filter(_is_parseable_text)
    )


def _utf8_entry(index: int) -> st.SearchStrategy[SubtitleEntry]:
    return st.builds(
        lambda times, text: SubtitleEntry(
            index=index,
            start_ms=min(times),
            end_ms=max(times),
            text=text,
        ),
        times=st.tuples(
            st.integers(min_value=0, max_value=_MAX_MS),
            st.integers(min_value=0, max_value=_MAX_MS),
        ),
        text=_utf8_multi_line_text_strategy(),
    )


@st.composite
def utf8_entry_lists(draw: st.DrawFn) -> List[SubtitleEntry]:
    """Generate a list of entries with Unicode-rich text.

    Indices are sequential ``1..n`` so the same generator serves both
    the SRT and VTT assertions (VTT parsing reassigns sequential
    indices, and SRT has no cross-entry ordering constraint beyond
    uniqueness).
    """
    size = draw(st.integers(min_value=0, max_value=4))
    if size == 0:
        return []
    return [draw(_utf8_entry(idx)) for idx in range(1, size + 1)]


@given(entries=utf8_entry_lists())
@settings(max_examples=150)
def test_to_srt_output_is_utf8_safe(entries: List[SubtitleEntry]) -> None:
    """**Validates: Requirement 3.4**

    For any valid ``entries`` list containing CJK, emoji, tabs, and
    embedded newlines, :meth:`SubtitleSerializer.to_srt` produces a
    ``str`` whose UTF-8 byte encoding decodes back to the original
    string without loss.
    """
    serializer = SubtitleSerializer()
    serialized = serializer.to_srt(entries)
    assert serialized.encode("utf-8").decode("utf-8") == serialized


@given(entries=utf8_entry_lists())
@settings(max_examples=150)
def test_to_vtt_output_is_utf8_safe(entries: List[SubtitleEntry]) -> None:
    """**Validates: Requirement 3.4**

    Same as :func:`test_to_srt_output_is_utf8_safe` but for the VTT
    serializer path.
    """
    serializer = SubtitleSerializer()
    serialized = serializer.to_vtt(entries)
    assert serialized.encode("utf-8").decode("utf-8") == serialized


@given(entries=utf8_entry_lists())
@settings(max_examples=100)
def test_write_file_srt_round_trips_bytes_via_utf8(
    entries: List[SubtitleEntry],
    tmp_path_factory: "pytest.TempPathFactory",  # noqa: F821 — resolved at runtime
) -> None:
    """**Validates: Requirement 3.4**

    Writing the SRT output to disk with :meth:`SubtitleSerializer.write_file`
    and reading the raw bytes back yields a UTF-8 byte string that decodes
    to exactly the serialized text — no BOM, no newline translation, no
    lossy encoding fallback.
    """
    serializer = SubtitleSerializer()
    serialized = serializer.to_srt(entries)

    # ``tmp_path_factory`` gives us a per-example directory so Hypothesis
    # shrinking does not clobber earlier iterations' output.
    target = tmp_path_factory.mktemp("srt_utf8") / "out.srt"
    serializer.write_file(target, serialized)

    raw = target.read_bytes()
    assert raw.decode("utf-8") == serialized


@given(entries=utf8_entry_lists())
@settings(max_examples=100)
def test_write_file_vtt_round_trips_bytes_via_utf8(
    entries: List[SubtitleEntry],
    tmp_path_factory: "pytest.TempPathFactory",  # noqa: F821 — resolved at runtime
) -> None:
    """**Validates: Requirement 3.4**

    Same as :func:`test_write_file_srt_round_trips_bytes_via_utf8` but
    for the VTT serializer path.
    """
    serializer = SubtitleSerializer()
    serialized = serializer.to_vtt(entries)

    target = tmp_path_factory.mktemp("vtt_utf8") / "out.vtt"
    serializer.write_file(target, serialized)

    raw = target.read_bytes()
    assert raw.decode("utf-8") == serialized
